# Be sure to restart your server when you modify this file.

# three bronto accounts are configured here with identity of the store code.

disable_cart_recovery: false
# if this option is false, the tagkey must be present in your yaml file

handle_asynchronously: true
# if this option is true, delayed_job must be configured.

default:
   token: YOUR_BRONTO_TOKEN_TO_ACCESS_API
   from_name: EMAIL_FROM NAME
   tagkey: YOUR_BRONTO_CART_RECOVERY_KEY_IF_CART_RECOVERY_IS_ENABLED
   order_shipped: EMAIL_API_ID_FOR_ORDER_SHIPPED_NOTIFICATION
   order_received: EMAIL_API_ID_FOR_ORDER_CONFIRMATION
   new_account: EMAIL_API_ID_FOR_ACCOUNT_CREATED
   password_reset: EMAIL_API_ID_FOR_PASSWORD_RESET
   order_canceled: EMAIL_API_ID_FOR_ORDER_CANCELED

store_a_code:
   token: YOUR_BRONTO_TOKEN_TO_ACCESS_API
   from_name: EMAIL_FROM NAME
   tagkey: YOUR_BRONTO_CART_RECOVERY_KEY_IF_CART_RECOVERY_IS_ENABLED
   order_shipped: EMAIL_API_ID_FOR_ORDER_SHIPPED_NOTIFICATION
   order_received: EMAIL_API_ID_FOR_ORDER_CONFIRMATION
   new_account: EMAIL_API_ID_FOR_ACCOUNT_CREATED
   password_reset: EMAIL_API_ID_FOR_PASSWORD_RESET
   order_canceled: EMAIL_API_ID_FOR_ORDER_CANCELED

store_b_code:
   token: YOUR_BRONTO_TOKEN_TO_ACCESS_API
   from_name: EMAIL_FROM NAME
   tagkey: YOUR_BRONTO_CART_RECOVERY_KEY_IF_CART_RECOVERY_IS_ENABLED
   order_shipped: EMAIL_API_ID_FOR_ORDER_SHIPPED_NOTIFICATION
   order_received: EMAIL_API_ID_FOR_ORDER_CONFIRMATION
   new_account: EMAIL_API_ID_FOR_ACCOUNT_CREATED
   password_reset: EMAIL_API_ID_FOR_PASSWORD_RESET
   order_canceled: EMAIL_API_ID_FOR_ORDER_CANCELED